---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Gather volume information from ONTAP
      netapp.ontap.na_ontap_info:
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: false
        gather_subset:
          - volume_info
      register: ontap_info

    - debug:
        var: ontap_info
