- name: Collect Azure VM Facts
  hosts: localhost
  tasks:
    - name: Gather Azure facts
      azure.azcollection.azure_rm_virtualmachine_info:
        resource_group: vm-rg
        name: VM
        register: vm_info

    - name: Display VM Facts
      debug:
        var: vm_info
